#!/bin/bash                                                                          
# CHECKER 0.0.2 Copyright 2015 @neilscudder
# Licenced under the GNU GPL <http://www.gnu.org/licenses/>.

main()
{
  [ $# -lt 2 ] && echo "Usage: $0 PLAYNODE SERVICENAME MAC"
  local playnode="$1"
  local serviceName="$2"
  local mac="$3"
  local flatFile="portalias-${serviceName}"  
  local portalias="$(cat \
    "${flatFile}" \
    | grep "^${playnode}" \
    | /usr/bin/cut -d^ -f2)"

  if [ ! -z ${portalias} ]; then
    echo "$portalias"
  elif [ ! -z ${playnode} ]; then
    local portalias="$(cat \                                                              
      "${flatFile}" \
      | tail -n1 \
      | /usr/bin/cut -d^ -f2)"
    (( ++portalias ))
    echo "$playnode^$portalias" >> "${flatFile}"                              
    echo "$portalias"                                                                   
  else                                                                                       
    echo "Playnode name was not ok."
  fi
}

main "$@"
exit 0
