#!/bin/sh
# PARADIGM 0.5.2 Copyright 2014 neil@neilscudder.com
# GNU GPL <http://www.gnu.org/licenses/>.


argCounter() {
  correctNumber=$1; actualNumber=$2; function=$3
  if [ $actualNumber -lt $correctNumber ]; then
    logIt E "$function did not receive enough arguments."
  else
    logIt I "$function"
  fi
}


logIt(){
  argCounter 2 $# $FUNCNAME
  a="$(date) ${PLAYNODE} - ${SERVICENAME} - "
  case $1 in
    I)
      b="${a}II"
    ;;
    W)
      b="${a}WW"
    ;;
    E)
      b="${a}EE"
      echo "${b} - ${2}" >> $LOGFILE
      echo "${b} - ${2}"
      exit 1
    ;;
  esac
  echo "${b} - ${2}" >> $LOGFILE
}


getPortalias() {
  local portCmd="cat\
    'portalias-${SERVICENAME}' \
    | grep '^${PLAYNODE}' \
    | /usr/bin/cut -d^ -f2"
  local portalias=$(
    /usr/bin/ssh \
    -q \
    -p ${SERVERPORT} \
    -o ControlMaster=no \
    ${CONTROLUSER}@${CONTROLSERVER} \
    "${portCmd}" \
  2>&1 )
  if [ -z $portalias ]; then
    logIt E "Portalias not set. Connection failed or playnode not found."
  else
    logIt I "Portalias is ${portalias}"
    echo "${portalias}"
  fi
}


establishTunnel() {
  argCounter 2 $# $FUNCNAME
  /usr/bin/ssh \
  -q \
  -p ${SERVERPORT} \
  -o ServerAliveCountMax=2 \
  -o ServerAliveInterval=45 \
  -o ControlMaster=no \
  -o ExitOnForwardFailure=yes \
  -N \
  -R ${portalias}:localhost:${SERVICEPORT} \
  ${CONTROLUSER}@${CONTROLSERVER} & \
  echo $! > "${pidFile}"
}


establishProxy() {
    argCounter 1 $# $FUNCNAME
    local pidFile=$1
    /usr/bin/ssh \
    -q \
    -p ${SERVERPORT} \
    -o ServerAliveCountMax=2 \
    -o ControlMaster=no \
    -o ExitOnForwardFailure=yes \
    -o ServerAliveInterval=45 \
    -N \
    -D ${SERVICEPORT} \
    ${CONTROLUSER}@${CONTROLSERVER} & \
    echo $! > ${pidFile} &
}


main() {
  #getOptions
  local pidFile=/tmp/paradigm-${SERVICENAME}.pid
  if [ -f ${pidFile} ]; then
    logIt I "${pidFile} found."
    local pid=$(cat ${pidFile})
    if kill -0 $pid > /dev/null 2>&1; then
      logIt I "Tunnel ${pid} found running"
    else
      logIt W "Tunnel ${pid} not found in process list"
      rm ${pidFile}
      if [ $PROXYMODE ]; then
        establishProxy "${pidFile}"
      else
        portalias=$(getPortalias ${pidFile})
        establishTunnel ${portalias} "${pidFile}"
      fi
    fi
  else
    if [ $PROXYMODE ]; then
      establishProxy "${pidFile}"
    else
      logIt W "${pidFile} not found"
      portalias=$(getPortalias ${pidFile})
      establishTunnel ${portalias} "${pidFile}"
    fi
  fi
}


showHelp() {
  cat << EOF

Usage: [OPTION] PLAYNODE SERVICENAME SERVICEPORT SERVER

-h
  Print this usage text.
-u 
  User account on server. Default=paradigm.
-p
  Server listening port. Default=22.
-X 
  Proxy mode.

A playnode is a name to define a group of service ports, usually the hostname.
User account on remote server with shell access required.
Server side flatfile is named portalias-SERVICENAME.
Entries are formatted one playnode per line like this: dummy^32767
Where dummy is the playnode name, and 32767 is the server local port
A server-side script registers new playnodes to new ports in this file.

Examples: 
  paradigm PlaynodeName Shell 22 control.server.com
  paradigm -u user -p 443 -l /var/lib/paradigm/log.paradigm PlaynodeName MPD 6600 control.server.com

EOF
}

#getOptions() {
# GET USER OPTIONS
# http://stackoverflow.com/a/14203146
OPTIND=1
while getopts "hl:u:p:X" opt; do
  case "$opt" in
  h)
    showHelp
    exit 0
    ;;
  l)  
    readonly LOGFILE="$OPTARG"
    ;;
  u)  
    readonly CONTROLUSER="$OPTARG"
    ;;
  p)  
    readonly SERVERPORT=$OPTARG
    ;;
  X)  
    readonly PROXYMODE=1
    ;;
  esac
done
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# from http://stackoverflow.com/a/13864829/5045643
[ -z ${CONTROLUSER+x} ] && readonly CONTROLUSER="paradigm"
[ -z ${SERVERPORT+x} ] && readonly SERVERPORT=22
[ -z ${LOGFILE+x} ] && readonly LOGFILE="$HOME/log.paradigm"

argCounter 4 $# BASE

readonly PLAYNODE="$1"
readonly SERVICENAME="$2"
readonly SERVICEPORT=$3
readonly CONTROLSERVER="$4"
#}

# Call the main function once to start
main 

echo "Paradigm for ${SERVICENAME} logged to ${LOGFILE}"
exit 0
