#!/bin/bash

# PARADIGM-WATCHER 0.1
# Monitors for changes in music directory size
# to update MPD after file transfers/deletions

# Copyright 2014 Neil Scudder neil@neilscudder.com
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

readonly MUSICDIR=$1
# Server URL and credentials:
#readonly CONTROLUSER=
#readonly CONTROLPASS=
#readonly CONTROLSERVER=
# Playnode needs to reach out over this port
# and the server needs to be listening on it:
# STATEFUL firewalls must open this port to $CONTROLSERVER
readonly SERVERLISTENINGPORT=42

main() {
	if ! mkdir /tmp/paradigm-watcher.lock; then
	    #printf "Paradigm watcher already running. Failed to aquire lock.\n" >&2
	    exit 1
	fi
	trap 'rm -rf /tmp/paradigm-watcher.lock' EXIT  # remove the lockdir on exit

	local sizeNew=$(/usr/bin/du -s ${MUSICDIR})
	local sizeOld=$(cat /var/lib/paradigm/size.old)

	if [ "$sizeOld" = "$sizeNew" ]
	then
	        echo "$(date) - II - Music library is the same size as 1 min ago."
	else
	        echo "$(date) - WW - Music library is a different size than 1 min ago."
		local i=1
		while [ $i -lt 4 ]
		do
			# Store the size for future comparison
			echo "${sizeNew}" > /var/lib/paradigm/size.old
			echo "$(date) - II - Waiting 20 seconds to see if size keeps changing..."
			sleep 20
			# Keep looping each minute until values are same
			sizeNew=$(/usr/bin/du -s ${MUSICDIR})
			sizeOld=$(cat /var/lib/paradigm/size.old)
			if [ "${sizeOld}" = "${sizeNew}" ]
			then
			        echo "$(date) - WW - Size has stopped changing, wait 20 more seconds to verify."
			        echo "${sizeNew}" > /var/lib/paradigm/size.old
				sleep 20
				sizeNew=$(/usr/bin/du -s ${MUSICDIR})
				sizeOld=$(cat /var/lib/paradigm/size.old)
				if [ "${sizeOld}" = "${sizeNew}" ]
				then
					echo "$(date) - Updating music database to reflect change in music library."
					/usr/bin/mpc update --wait >/dev/null
					exit 0
					# Post log to server after database update finishes
#					portalias=$(/usr/bin/sshpass \
#						-p${CONTROLPASS} \
#							/usr/bin/ssh \
#							-q \
#							-p ${SERVERLISTENINGPORT} \
#							-o StrictHostKeyChecking=no \
#							-o ControlMaster=no \
#							${CONTROLUSER}@${CONTROLSERVER} \
#							"echo $(date) >> /home/controller/DEBUG.synctimes" \
#						2>&1)
				else
					echo "$(date) - WW - Oh hang on, they're different again."
				fi
			fi
		done
	fi
}

main

exit 0

